/* Create the necessary settings */
CALL editSetting(NULL, 'mqttServer', 'my.mqttserver.com', @responseCode);
CALL editSetting(NULL, 'mqttPort', '1883', @responseCode);
CALL editSetting(NULL, 'mqttUsername', '$DEVICENAME$', @responseCode);
CALL editSetting(NULL, 'mqttPassword', '$DEVICENAME$', @responseCode);
CALL editSetting(NULL, 'clientTopic', 'myhouse/client/$DEVICENAME$', @responseCode);
CALL editSetting(NULL, 'controlTopic', 'myhouse/control/', @responseCode);
CALL editSetting(NULL, 'eventTopic', 'myhouse/button/', @responseCode);
CALL editSetting(NULL, 'wifiSSID', 'myWiFiSSID', @responseCode);
CALL editSetting(NULL, 'wifiKey', 'myWiFiPassword', @responseCode);
CALL editSetting(NULL, 'bootstrapURL', 'http://myBootstrapServer.com/$DEVICENAME$', @responseCode);
CALL editSetting(NULL, 'bootstrapRefreshMs', 3600000, @responseCode);
CALL editSetting(NULL, 'firmwareRefreshMs', 3600000, @responseCode);

/* Create the button colors */
CALL editButtonColor(NULL, 'Blue', '#034efc', 0, 100, @responseCode);
CALL editButtonColor(NULL, 'White', '#ffffff', 0, 100, @responseCode);
CALL editButtonColor(NULL, 'Green', '#488a20', 0,  100, @responseCode);
CALL editButtonColor(NULL, 'Red', '#a82727', 0,  100, @responseCode);
CALL editButtonColor(NULL, 'Amber', '#c79112', 0, 100, @responseCode);
CALL editButtonColor(NULL, 'None', '#000000', 0, 100, @responseCode);

/* Create brightness names */
CALL editBrightnessName(NULL, 'Off', 0, @responseCode);
CALL editBrightnessName(NULL, 'Bright', 100, @responseCode);
CALL editBrightnessName(NULL, 'Dim', 30, @responseCode);
CALL editBrightnessName(NULL, 'Default', 80, @responseCode);

/* Create the controller pins */
CALL editControllerPins(NULL, 2, 2, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 3, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 4, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 5, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 6, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 7, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 8, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 9, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 11, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 13, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 22, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 23, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 24, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 25, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 26, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 27, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 28, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 29, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 30, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 31, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 32, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 33, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 34, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 35, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 36, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 37, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 38, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 39, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 40, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 41, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 42, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 43, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 44, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 45, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 46, true, true, true, @responseCode);
CALL editControllerPins(NULL, 2, 47, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 48, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 49, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 55, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 56, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 57, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 58, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 59, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 60, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 61, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 62, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 63, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 64, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 65, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 66, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 67, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 68, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 69, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 70, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 71, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 72, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 73, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 74, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 75, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 76, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 77, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 78, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 79, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 80, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 81, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 82, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 83, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 84, true, true, false, @responseCode);
CALL editControllerPins(NULL, 2, 85, true, true, false, @responseCode);

/* Create the controller ports */
CALL editControllerPorts(NULL, 2, 1, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 2, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 3, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 4, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 5, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 6, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 7, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 8, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 9, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 10, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 11, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 12, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 13, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 14, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 15, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 16, true, false, @responseCode);
CALL editControllerPorts(NULL, 2, 17, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 18, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 19, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 20, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 21, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 22, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 23, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 24, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 25, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 26, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 27, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 28, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 29, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 30, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 31, false, true, @responseCode);
CALL editControllerPorts(NULL, 2, 32, false, true, @responseCode);